import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
                'headline-sm': ['Nunito Sans', 'Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'headline-md': ['Nunito Sans', 'Inter', 'sans-serif'],
                'headline-md-mobile': ['Nunito Sans', 'Inter', 'sans-serif'],
                'display-lg': ['Nunito Sans', 'Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'mono-md': ['JetBrains Mono', 'monospace'],
            },
            fontSize: {
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '700' }],
                'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'mono-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
            },
            colors: {
                primary: {
                    DEFAULT: '#00C4A7',
                    dark: '#0298A6',
                    hover: '#00b296',
                    container: '#E6FAF7',
                },
                'primary-fixed': '#E6FAF7',
                'primary-fixed-dim': '#B2E9E2',
                'on-primary': '#ffffff',
                'on-primary-fixed': '#003430',
                'on-primary-fixed-variant': '#00796B',
                'primary-container': '#E6FAF7',
                'on-primary-container': '#00665C',
                secondary: {
                    DEFAULT: '#028090',
                    50: '#E0F2F4',
                    100: '#B3DEE3',
                    200: '#80C7D0',
                    300: '#4DB0BD',
                    400: '#1A99A9',
                    500: '#028090',
                    600: '#027080',
                    700: '#015968',
                    800: '#01424E',
                    900: '#002C35',
                },
                'secondary-fixed': '#B2E9E2',
                'secondary-fixed-dim': '#7FD6CC',
                'on-secondary': '#ffffff',
                'on-secondary-fixed': '#00332F',
                'on-secondary-fixed-variant': '#006D63',
                'secondary-container': '#B2E9E2',
                'on-secondary-container': '#00574F',
                tertiary: {
                    DEFAULT: '#DD6B20',
                    50: '#FDF3E9',
                    100: '#FADFC5',
                    200: '#F5C394',
                    300: '#EFA763',
                    400: '#E98B32',
                    500: '#DD6B20',
                    600: '#C15A1A',
                    700: '#9C4715',
                    800: '#773610',
                    900: '#52250B',
                },
                'tertiary-fixed': '#FEF3C7',
                'tertiary-fixed-dim': '#F8D98E',
                'on-tertiary': '#ffffff',
                'on-tertiary-fixed': '#5D2E00',
                'on-tertiary-fixed-variant': '#8A4600',
                'tertiary-container': '#FEF3C7',
                'on-tertiary-container': '#A24E0E',
                error: {
                    DEFAULT: '#E53E3E',
                    50: '#FEF2F2',
                    100: '#FEE2E2',
                },
                'error-container': '#FEE2E2',
                'on-error': '#ffffff',
                'on-error-container': '#9B2C2C',
                surface: {
                    DEFAULT: '#ffffff',
                    dim: '#D9E4E4',
                    bright: '#ffffff',
                    container: '#EBF6F6',
                    'container-lowest': '#ffffff',
                    'container-low': '#F4FBFB',
                    'container-high': '#E1F0F0',
                    'container-highest': '#D7E9E9',
                    variant: '#DDECEC',
                    tint: '#0298A6',
                },
                'on-surface': '#1A2E35',
                'on-surface-variant': '#5B737C',
                'teal-accent': '#00C4A7',
                outline: '#D1E2E4',
                'outline-variant': '#E3EFF0',
                background: '#F5FAFA',
                'on-background': '#1A2E35',
                'inverse-primary': '#66D9C9',
                'inverse-surface': '#2E3B40',
                'inverse-on-surface': '#E8F5F5',
            },
            borderRadius: {
                DEFAULT: '0.375rem',
                lg: '0.625rem',
                'md3-xs': '4px',
                'md3-sm': '8px',
                'md3-md': '12px',
                'md3-lg': '0.875rem',
                xl: '0.875rem',
                'md3-xl': '28px',
                '2xl': '1.125rem',
                'md3-full': '9999px',
                full: '9999px',
            },
            spacing: {
                'md3-xs': '4px',
                'md3-sm': '8px',
                'md3-md': '16px',
                'md3-lg': '24px',
                'md3-xl': '32px',
                'md3-2xl': '48px',
                'card-padding': '1.25rem',
                'stack-sm': '0.5rem',
                'stack-md': '1rem',
                gutter: '1.5rem',
                sidebar: '265px',
                'container-max': '1280px',
                'sidebar-collapsed': '72px',
            },
            boxShadow: {
                'md3-1': '0 1px 2px rgba(0,0,0,0.3), 0 1px 3px 1px rgba(0,0,0,0.15)',
                'md3-2': '0 1px 2px rgba(0,0,0,0.3), 0 2px 6px 2px rgba(0,0,0,0.15)',
                'md3-3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px rgba(0,0,0,0.3)',
                custom: '0 1px 3px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.02)',
                'brand-soft': '0 2px 12px rgba(0,196,167,0.03)',
            },
        },
    },

    plugins: [forms],
};