import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
                'headline-sm': ['Inter'],
                'label-md': ['Inter'],
                'headline-md': ['Inter'],
                'headline-md-mobile': ['Inter'],
                'display-lg': ['Inter'],
                'body-md': ['Inter'],
                'body-lg': ['Inter'],
                'mono-md': ['JetBrains Mono'],
            },
            fontSize: {
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'mono-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
            },
            colors: {
                primary: {
                    DEFAULT: '#003d9b',
                    50: '#e6eefb',
                    100: '#b3d1f3',
                    200: '#80b4eb',
                    300: '#4d97e3',
                    400: '#1a7adb',
                    500: '#003d9b',
                    600: '#003588',
                    700: '#002a6b',
                    800: '#001f4f',
                    900: '#001432',
                },
                'primary-fixed': '#dae2ff',
                'primary-fixed-dim': '#b2c5ff',
                'on-primary': '#ffffff',
                'on-primary-fixed': '#001848',
                'on-primary-fixed-variant': '#0040a2',
                'primary-container': '#0052cc',
                'on-primary-container': '#c4d2ff',
                secondary: {
                    DEFAULT: '#006c47',
                    50: '#e6f5ee',
                    100: '#b3e2d1',
                    200: '#80cfb3',
                    300: '#4dbd96',
                    400: '#1aaa78',
                    500: '#006c47',
                    600: '#00603f',
                    700: '#004c32',
                    800: '#003725',
                    900: '#002318',
                },
                'secondary-fixed': '#82f9be',
                'secondary-fixed-dim': '#65dca4',
                'on-secondary': '#ffffff',
                'on-secondary-fixed': '#002113',
                'on-secondary-fixed-variant': '#005235',
                'secondary-container': '#82f9be',
                'on-secondary-container': '#00734c',
                tertiary: {
                    DEFAULT: '#5e3c00',
                    50: '#f5efe6',
                    100: '#e0ccaa',
                    200: '#cba96e',
                    300: '#b68632',
                    400: '#8a6520',
                    500: '#5e3c00',
                    600: '#523500',
                    700: '#402a00',
                    800: '#2e1e00',
                    900: '#1c1200',
                },
                'tertiary-fixed': '#ffddb3',
                'tertiary-fixed-dim': '#ffb950',
                'on-tertiary': '#ffffff',
                'on-tertiary-fixed': '#291800',
                'on-tertiary-fixed-variant': '#624000',
                'tertiary-container': '#7d5200',
                'on-tertiary-container': '#ffca81',
                error: {
                    DEFAULT: '#ba1a1a',
                    50: '#fef2f2',
                    100: '#fee2e2',
                },
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
                'on-error-container': '#93000a',
                surface: {
                    DEFAULT: '#faf8ff',
                    dim: '#d9d9e4',
                    bright: '#faf8ff',
                    container: '#ededf8',
                    'container-lowest': '#ffffff',
                    'container-low': '#f3f3fd',
                    'container-high': '#e7e7f2',
                    'container-highest': '#e1e2ec',
                    variant: '#e1e2ec',
                    tint: '#0c56d0',
                },
                'on-surface': '#191b23',
                'on-surface-variant': '#434654',
                outline: '#737685',
                'outline-variant': '#c3c6d6',
                background: '#faf8ff',
                'on-background': '#191b23',
                'inverse-primary': '#b2c5ff',
                'inverse-surface': '#2e3038',
                'inverse-on-surface': '#f0f0fb',
            },
            borderRadius: {
                'md3-xs': '4px',
                'md3-sm': '8px',
                'md3-md': '12px',
                'md3-lg': '16px',
                'md3-xl': '28px',
                'md3-full': '9999px',
            },
            spacing: {
                'md3-xs': '4px',
                'md3-sm': '8px',
                'md3-md': '16px',
                'md3-lg': '24px',
                'md3-xl': '32px',
                'md3-2xl': '48px',
                'card-padding': '1.25rem',
                'stack-sm': '0.5rem',
                'stack-md': '1rem',
                'gutter': '1.5rem',
                'sidebar': '260px',
                'container-max': '1280px',
                'sidebar-collapsed': '72px',
            },
            boxShadow: {
                'md3-1': '0 1px 2px rgba(0,0,0,0.3), 0 1px 3px 1px rgba(0,0,0,0.15)',
                'md3-2': '0 1px 2px rgba(0,0,0,0.3), 0 2px 6px 2px rgba(0,0,0,0.15)',
                'md3-3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px rgba(0,0,0,0.3)',
                'custom': '0 1px 3px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.02)',
            },
        },
    },

    plugins: [forms],
};
