server {
    listen 80;
    listen [::]:80;
    server_name dentamor.jemigra.com;
    root /var/www/dentamor/public;
    location /.well-known/acme-challenge/ { }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name dentamor.jemigra.com;

    ssl_certificate /etc/letsencrypt/live/dentamor.jemigra.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dentamor.jemigra.com/privkey.pem;

    root /var/www/dentamor/public;
    index index.php index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass dentamor_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_param X-Forwarded-Proto https;
        fastcgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}