server {
    listen 80;
    listen [::]:80;
    server_name dentamor.jemigra.com;
    root /var/www/dentamor/public;
    location /.well-known/acme-challenge/ { }
    location / { return 301 https://$host$request_uri; }
}